import os
import json
import io
from fastapi import FastAPI, File, UploadFile, HTTPException
from fastapi.responses import JSONResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
import google.generativeai as genai
from PIL import Image

app = FastAPI(
    title="Aadhaar OCR API",
    description="API to extract structured information from Indian Aadhaar cards using Gemini 1.5 Flash",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Ensure the API key correctly relies on Environment Variables ONLY for security
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)
else:
    print("Warning: GEMINI_API_KEY is not set.")

# Initialize the Gemini model
model = genai.GenerativeModel("gemini-flash-latest")

class AadhaarData(BaseModel):
    name: str = Field(default="")
    dob: str = Field(default="")
    gender: str = Field(default="")
    aadhaar_number: str = Field(default="")
    address: str = Field(default="")

def parse_json_response(text: str) -> dict:
    """Parses the JSON response from Gemini, handling potential markdown."""
    text = text.strip()
    if text.startswith("```json"):
        text = text[7:]
    elif text.startswith("```"):
        text = text[3:]
    if text.endswith("```"):
        text = text[:-3]
    text = text.strip()

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return {}

def format_data(data: dict) -> dict:
    """Formats and cleans up the extracted data."""
    # Ensure Aadhaar is strictly digits, length checked
    aadhaar_num = data.get("aadhaar_number", "")
    clean_aadhaar = "".join(filter(str.isdigit, str(aadhaar_num)))
    if len(clean_aadhaar) == 12:
        data["aadhaar_number"] = clean_aadhaar
    else:
        data["aadhaar_number"] = ""
        
    # Ensure DOB is formatted if possible
    dob = str(data.get("dob", "")).replace("-", "/").replace(".", "/")
    data["dob"] = dob
    
    return data

@app.post("/extract-aadhaar", response_model=AadhaarData)
async def extract_aadhaar(
    front_image: UploadFile = File(...),
    back_image: UploadFile = File(...)
):
    try:
        # Read the images into memory
        front_bytes = await front_image.read()
        back_bytes = await back_image.read()

        # Load images via PIL for the Gemini API and limit size to compress memory usage
        front_pil = Image.open(io.BytesIO(front_bytes))
        front_pil.thumbnail((1024, 1024))
        
        back_pil = Image.open(io.BytesIO(back_bytes))
        back_pil.thumbnail((1024, 1024))

        # Prompt specifying the task and expected strict JSON output
        prompt = """
        You are an expert OCR AI that extracts structured data from Indian Aadhaar cards.
        I am giving you two images: the front side and the back side of an Aadhaar card.
        
        Please read both Aadhaar images, extract text, identify the correct fields, and return strict JSON format.
        Do not add any markdown, explanation or text outside the JSON block.

        Expected JSON format:
        {
          "name": "<extracted full name>",
          "dob": "<extracted date of birth in DD/MM/YYYY format>",
          "gender": "<extracted gender: Male, Female, or Transgender>",
          "aadhaar_number": "<extracted 12-digit Aadhaar number as a continuous string without spaces>",
          "address": "<extracted full address from the back side>"
        }
        
        If a field cannot be found, leave it as an empty string ("").
        """

        # Call Gemini model
        response = model.generate_content([prompt, front_pil, back_pil])
        
        if not response.text:
            raise ValueError("No text generated by the model.")

        # Parse and format the data
        parsed_data = parse_json_response(response.text)
        formatted_data = format_data(parsed_data)

        # Validate with Pydantic
        result = AadhaarData(**formatted_data)
        
        return result

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
